[project]
name = "ilay-media"
version = "0.1.0"
description = "一个基于资源搜索机器人"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "python-dotenv>=1.1.0",
    "python-telegram-bot>=22.0",
    "PyJWT>=2.8.0",
    "nullbr>=1.0.0",
]

